### ISSUE TITLE
Sole entry in BEN

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/alternateheadwords#1]
Artti (Arti)
alternate headword is 'Arti'

Not keeping the BEN subdirectory in this repository.

**Comment by drdhaval2785** [comment]
@gasyoun 
github manners says that `wontfix` is equivalent to `f..k off`.
Changing this to correction submission.

**Comment by gasyoun** [comment]
> github manners says that wontfix is equivalent to f..k off.

That was by accident. :tada:

**Comment by drdhaval2785** [comment]
Can @funderburkjim create a small patch for this particular word, so that we can close this issue?

**Comment by funderburkjim** [comment]
Now that we have an approach for dealing with alternate headwords, I should be able to do this.
Will add to todo list.
