### ISSUE TITLE
How to find root 'nI' in WIL

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/alternateheadwords#16]
While working with corrections to Wilson dictionary, I had occasion to search for the root नी (to lead).

But such a common root is not found !  Surely it is there somewhere.

Discovered it is there under spelling णी !  Same story for SKD.  VCP has both spellings.

This is a good example of the type of extension to spelling normalization that has been begun with hwnorm1.  Clearly, we need to extend this normalization to such cases as नी = णी .

This is probably an area of research that should be promoted to near-term.  With all our study of the
headwords of dictionaries, and comparisons of root spellings also,  we should be able to make a 
good attempt at a full mutli-dictionary headword list, that will take into account such variants as नी , णी.

**Comment by drdhaval2785** [comment]
My quick and incomprehensive responses

1. ^z->s
zah -> sah
http://sanskritdocuments.org/learning_tools/sarvanisutrani/6.1.62.htm

2. ^R->n
RI -> nI
http://sanskritdocuments.org/learning_tools/sarvanisutrani/6.1.63.htm

3. delete starting wu, qu, Yi
e.g. wudu, qukfY, YimidA

4. Remove terminal consonant
e.g. qukfY.

5. convert terminal i to penultimate homorganic nasal.
e.g. aki -> aNk

These five should be the major criteria for verb normalization in hwnorm1.


SKD follows kavikalpadruma dhAtupATha. Its anubandhas are different than
Panini's.

**Comment by drdhaval2785** [comment]
I feel this discussion belongs to hwnorm1 repository rather than alternate
headwords repo..

**Comment by funderburkjim** [comment]
> belongs to hwnorm1 repository

Agree. I chose repository too hastily.

**Comment by gasyoun** [comment]
> SKD follows kavikalpadruma dhAtupATha. Its anubandhas are different than
Panini's.

Even Palsule, best Indian expert on dhatupathas, was impressed (to say the least) on kavikalpadruma's Bengal authors creativity.

> These five should be the major criteria for verb normalization in hwnorm1.

Thanks a lot, Dhaval!
