### ISSUE TITLE
upper-case and lower-case repositories on Windows

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/alternateheadwords#22]
### Windows Git and case-sensitivity

Yesterday I was doing some work on this repository on my local Windows 10 PC.  
Specifically, I was working with the data/VCP directory.   

Somewhere along the line, I (unintentionally) created a 'data/vcp' directory.   

After syncing this work to GitHub,  I noticed that there were now TWO folders (data/VCP and data/vcp).
However, only one directory name (data/vcp) showed in my local file system.

This shows that the Windows OS file-system convention of case-insensitivity was being silently
enforced in the display of the local file system, although the Unix file-system case sensitivity was being maintained within the `.git` repository.

Having two directories when examining files on GitHub (vcp and VCP) and only one directory when working on the local clone --- this situation is intolerably confusing.  I don't think it can be resolved on the local Windows clone.

### Use a Linux account to merge vcp into VCP
Here's how I got rid of the problem:
* log in to an account at pythonanywhere.com.   This is a unix-based system.
* Open a bash console, and clone:
   `git clone git@github.com:sanskrit-lexicon/alternateheadwords.git`
* move files from `data/vcp` to `data/VCP`   (there was no overlap in the file names)
* remove the 'data/vcp' directory
* set my git identity on pythonanywhere to be the same as it is at GitHub:
  * git config --global user.email <my-github-email>
  * git config --global user.name <my-github-name>
  * NOTE:  I found these by `git config --global --list` on my local Windows machine under GitBash shell
* Add and commit the changes:
  ` git add -A`  
  `git commit -m "move lower-vcp to VCP"
* Push changes back to GitHub
  `git push origin master`

### Update local copy of repository
I did this with 'sync' in the GitHub UI on local WIndows machine.

###  Correct same problem with 'skd' and "SKD'
There was also a data/skd and data/SKD.  Also corrected this siimlarly, using pythonAnywhere as
Linux intermediary.

### Moral of Story
In cloned repositories on Windows, be careful to preserve case with existing filenames.

**Comment by gasyoun** [comment]
> preserve case with existing filenames

Tough lesson.
