### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/alternateheadwords#4]
First of all धन्यवादः Dhaval. I guess it's fair enough you've split the burden with Jim. I give you my thanks. Many thanks. As I'm eager to get the biggest list of Sanskrit words and wordforms, sure it's a gift to me as well (and the rest of the worlds).
- `This program uses DICTNAMEhw0.txt (e.g. skdhw0.txt) file from Cologne.`
  But the skdhw0.txt files does not contain the changes implemented lately bu Jim. All changes are in separate files. Would not it raise (rarely) new issues?
- `Each line is in the format correctioncode:givenheadword:preferredheadword:scrap e.g. 3:kube(ve)raH:kuveraH:kubeveH`
  What if instead of 2 names the output should give 4 (after opening 2 brackets in 1 word)? There are such cases in VCP at least.

**Comment by drdhaval2785** [comment]
> This program uses DICTNAMEhw0.txt (e.g. skdhw0.txt) file from Cologne.
> But the skdhw0.txt files does not contain the changes implemented lately
> bu Jim. All changes are in separate files. Would not it raise (rarely) new
> issues?

I am sure it will not. Because changes have all happened in non bracket
part only.

> Each line is in the format
> correctioncode:givenheadword:preferredheadword:scrap e.g.
> 3:kube(ve)raH:kuveraH:kubeveH
> What if instead of 2 names the output should give 4 (after opening 2
> brackets in 1 word)? There are such cases in VCP at least.

I saw them too. Not handled mechanically as of yet. Will need manual
correction.

**Comment by funderburkjim** [comment]
@drdhaval2785   Do you need a separate download of all the xhw0.txt files ?

**Comment by drdhaval2785** [comment]
I ran the script from my local version of all Cologne dictionaries. There
are only 5-6 dictionaries which have this bracket phenomenon. So, I don't
think I will need it for all. Whatever I needed, I have.

**Comment by gasyoun** [comment]
> I am sure it will not. Because changes have all happened in non bracket
> part only.

Ok.

> Not handled mechanically as of yet. Will need manual
> correction.

Ok, they have been handled manually in the XLS file in 2014 already, if of interest.
